[platformio]
default_envs =
  ; lilygo-rtl_433-custom
  lilygo-rtl_433-custom-ota

[env:lilygo-rtl_433-custom]
platform = ${com.esp32_platform}
board = ttgo-lora32-v21
; ~/.platformio/packages/framework-arduinoespressif32/variants/.../pins_arduino.h
board_build.partitions = min_spiffs.csv
lib_deps =
  ${com-esp32.lib_deps}
  ${libraries.ssd1306}
  ${libraries.rtl_433_ESP}
build_flags =
  ${com-esp32.build_flags}
; *** OpenMQTTGateway Config ***
  ;'-UZmqttDiscovery'          ; disables HA MQTT Discovery
  '-DvalueAsATopic=true'    ; MQTT topic includes model and device
  '-DGateway_Name="lilygo_rtl_433_ESP_OOK"'
; *** OpenMQTTGateway Modules ***
  '-DZgatewayRTL_433="rtl_433"'
  '-DZradioSX127x="SX127x"'
; *** ssd1306 Display Options ***
  '-DZdisplaySSD1306="LilyGo_SSD1306"'
;  '-DLOG_TO_OLED=true'         ; Enable log to OLED
;  '-DJSON_TO_OLED=true'
;  '-DLOG_LEVEL_OLED=LOG_LEVEL_NOTICE'
;  '-DDISPLAY_IDLE_LOGO=false'
;  '-DDISPLAY_BRIGHTNESS=80'
;  '-DDISPLAY_METRIC=false'
  '-DESPWifiManualSetup=true'
  '-Dwifi_ssid="SECRET"'
  '-Dwifi_password="SECRET"'
  '-Dgw_password="SECRET"'  ; ota password, default to empty string
  '-DMQTT_USER="SECRET"'
  '-DMQTT_PASS="SECRET"'
  '-DMQTT_SERVER="SECRET"'
  '-DBase_Topic="openmqttgateway/"'
custom_description = Custom For ESP32, Gateway using RTL_433_ESP and RadioLib
custom_hardware = ESP32 LILYGO LoRa32 V2.1

[env:lilygo-rtl_433-custom-ota]
extends = env:lilygo-rtl_433-custom
upload_protocol = espota
upload_port = SECRET   ; device ip address
upload_flags =
  --auth="SECRET"   ; ota password
  --port=8266
